version: '3.9'

services:
  api-profile-image:
    image: api-profile-image
    container_name: api-profile-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    environment:
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - KEY_STORE_TYPE=${KEY_STORE_TYPE}
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql_db
    ports:
      - "3307:3306"
    networks:
      - spring-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql_data: