version: '3.9'

services:
  api-profile-image:
    image: api-profile-image
    container_name: api-profile-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    environment:
      - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
      - KEY_STORE_TYPE=${KEY_STORE_TYPE}
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
networks:
  spring-network: